source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PWSegmentedControl_Example', :exclusive => true do
  pod 'PWSegmentedControl', :path => '../'
end

target 'PWSegmentedControl_Tests', :exclusive => true do
  pod 'PWSegmentedControl', :path => '../'

  
end
